### ISSUE TITLE
fatal error: ATen/ATen.h: No such file or directory

### ISSUE THREAD

**Issue by deepmipt-VladZhukov** [facebookresearch/fairseq-py#4] opened 2017-09-25 11:28 UTC
After running :
```python setup.py build```
I get:
```
running build
running build_py
generating /tmp/tmpz4hbar33/_temporal_convolution_tbc.c
running build_ext
building '_temporal_convolution_tbc' extension
creating home
creating home/vlad
creating home/vlad/work
creating home/vlad/work/seq2seq
creating home/vlad/work/seq2seq/fairseq-py
creating home/vlad/work/seq2seq/fairseq-py/fairseq
creating home/vlad/work/seq2seq/fairseq-py/fairseq/clib
creating home/vlad/work/seq2seq/fairseq-py/fairseq/clib/temporal_convolution_tbc
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/vlad/anaconda3/envs/seq2seqTorch/include/python3.6m -c _temporal_convolution_tbc.c -o ./_temporal_convolution_tbc.o -std=c++11
cc1: warning: command line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DWITH_CUDA -I/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include -I/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/torch/utils/ffi/../../lib/include/THC -I/usr/local/cuda/include -I/home/vlad/anaconda3/envs/seq2seqTorch/include/python3.6m -c /home/vlad/work/seq2seq/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp -o ./home/vlad/work/seq2seq/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
/home/vlad/work/seq2seq/fairseq-py/fairseq/clib/temporal_convolution_tbc/temporal_convolution_tbc.cpp:12:23: fatal error: ATen/ATen.h: No such file or directory
compilation terminated.
Traceback (most recent call last):
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/unixccompiler.py", line 118, in _compile
    extra_postargs)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/cffi/ffiplatform.py", line 49, in _build
    dist.run_command('build_ext')
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/build_ext.py", line 77, in run
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 185, in run
    _build_ext.build_ext.run(self)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 193, in build_extensions
    self.build_extension(ext)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/build_ext.py", line 198, in build_extension
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/ccompiler.py", line 574, in compile
    self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/unixccompiler.py", line 120, in _compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    'build_py': build_py_hook,
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 49, in run
    conv_tbc.build()
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 164, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 100, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/cffi/api.py", line 684, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/cffi/recompiler.py", line 1484, in recompile
    compiler_verbose, debug)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/cffi/ffiplatform.py", line 20, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/cffi/ffiplatform.py", line 56, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: CompileError: command 'gcc' failed with exit status 1
```
CUDA
```
cat /usr/local/cuda/version.txt
CUDA Version 8.0.61
```

**Comment by edunov** [comment] 2017-09-25 14:17
@deepmipt-VladZhukov what pytorch version do you use? ATen.h is not in the release yet, so we suggest installing pytorch from the github for now. You can find exact instructions and the version we've tested in the README. You'll be able to use pytorch from binaries when the new release is out.

**Comment by deepmipt-VladZhukov** [comment] 2017-09-25 16:08
then I get:
```
File "setup.py", line 12, in <module>
    from torch.utils.ffi import create_extension
  File "/home/vlad/anaconda3/envs/seq2seqTorch/lib/python3.6/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
```

**Comment by edunov** [comment] 2017-09-25 17:05
@deepmipt-VladZhukov could you please post the exact list of commands you've run? I haven't seen this issue before, but it seems like the pytorch binaries are not consistent with python code. Have you built pytorch from the source?

**Comment by deepmipt-VladZhukov** [comment] 2017-09-27 09:24
I've created new conda environment, just followed instructions in readme - result is the same error. Seems the problem begins here:
```
vlad@node16:~$ nvcc --version
The program 'nvcc' is currently not installed. To run 'nvcc' please ask your administrator to install the package 'nvidia-cuda-toolkit'
```
(I also can't use sudo on this machine)

If I only need preprocessing for iwslt14, should I install whole lib?)

**Comment by deepmipt-VladZhukov** [comment] 2017-09-27 10:42
nope, added path, that's not the reason:
```
(s2sNew) vlad@node16:~/work/seq2seq/fairseq-py$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

**Comment by myleott** [comment] 2017-09-27 15:54
Are you building on a Mac by any chance? I found this similar-looking issue in torch: https://github.com/torch/distro/issues/32#issuecomment-297603656.

Can you add line 218 below to the file `pytorch/torch/lib/TH/CMakeLists.txt` and rebuild?:
```
215  # IF ANY SIMD FOUND
216  IF(C_AVX2_FOUND OR C_AVX_FOUND OR C_SSE4_2_FOUND OR C_SSE4_1_FOUND)
217    SET(simd generic/simd/convolve.c)
218    SET(simd ${simd} generic/simd/convolve5x5_sse.c)
219  ENDIF(C_AVX2_FOUND OR C_AVX_FOUND OR C_SSE4_2_FOUND OR C_SSE4_1_FOUND)
```

**Comment by deepmipt-VladZhukov** [comment] 2017-09-27 20:27
sorry, I explained it  poorly. This error occurs when I run python setup.py in fairseq folder NOT in pytorch

**Comment by deepmipt-VladZhukov** [comment] 2017-09-27 20:29
the docker container with fairseq-py on the board will be nice...

**Comment by myleott** [comment] 2017-09-27 20:37
Yep, but fairseq-py requires building a custom module (TemporalConvolutionTBC) and it seems that that build process is missing "convolve5x5_sse" (from pytorch). This makes me think there may be something wrong with your pytorch install. Could you please confirm your system setup? What kind of CPU/OS are you using?

**Comment by deepmipt-VladZhukov** [comment] 2017-09-27 20:52
```
(s2sNew) vlad@node16:~/work/seq2seq/pytorch$ uname -a
Linux node16 4.10.0-28-generic #32~16.04.2-Ubuntu SMP Thu Jul 20 10:19:48 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by myleott** [comment] 2017-09-27 20:53
Does your CPU support SSE4? What's the output of `cat /proc/cpuinfo`?

**Comment by deepmipt-VladZhukov** [comment] 2017-09-27 20:54
```
(s2sNew) vlad@node16:~/work/seq2seq/pytorch$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad  CPU   Q9300  @ 2.50GHz
stepping	: 7
cpu MHz		: 2000.000
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 lahf_lm tpr_shadow vnmi flexpriority dtherm
bugs		:
bogomips	: 4999.54
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad  CPU   Q9300  @ 2.50GHz
stepping	: 7
cpu MHz		: 2000.000
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 lahf_lm tpr_shadow vnmi flexpriority dtherm
bugs		:
bogomips	: 4999.54
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad  CPU   Q9300  @ 2.50GHz
stepping	: 7
cpu MHz		: 2000.000
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 lahf_lm tpr_shadow vnmi flexpriority dtherm
bugs		:
bogomips	: 4999.54
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Quad  CPU   Q9300  @ 2.50GHz
stepping	: 7
cpu MHz		: 2000.000
cache size	: 3072 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 10
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts rep_good nopl aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 lahf_lm tpr_shadow vnmi flexpriority dtherm
bugs		:
bogomips	: 4999.54
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:

```

**Comment by myleott** [comment] 2017-09-27 21:08
Hmm, it looks like the Q9300 was the first generation of Intel CPU to support SSE4(.1), but my guess is that the pytorch install is not picking it up. Does it work if you edit the `pytorch/torch/lib/TH/CMakeLists.txt` file as described above, rebuild pytorch, and then build fairseq?

**Comment by myleott** [comment] 2017-10-10 20:27
Closing this since it's not reproducible by us, but please reopen if you discover any additional clues or if it looks like something we can help fix.

**Closed by myleott** 2017-10-10 20:27 UTC

**Comment by chssch** [comment] 2017-10-21 17:27
I have installed cu80/torch-0.2.0.post3-cp36-cp36m-manylinux1_x86_64.whl with pip under Linux and the complete ATen headers seem to be missing  in `/torch/lib/include`. I also checked wheel directly, don't know if this is left out on purpose or a packaging error.

**Workaround that works: Installing from source**

**Comment by edunov** [comment] 2017-10-21 21:38
@chssch I believe ATen is not released yet. You need to build torch from source until the next release is out.

**Comment by dashesy** [comment] 2018-05-30 20:33
After what version is ATen released?
